### ISSUE TITLE
Versioning logic

### ISSUE THREAD

**Issue by NeQuissimus** [dwijnand/sbt-dynver#12]
Could you explain the logic with which tags are considered?
I think I am misunderstanding the README.

I have a project that has a tag v0.1 (and I tried v1.0.0 as well, same result) that I cut from my `master` branch.
I then have three more commits in `master`. I would expect my `dynver` to now return something containing `0.1` but it simply prints the git hash.
The README seems to suggest I should expect something like `0.1+3-1234abcd`. Am I wrong?

Thank you :)

**Comment by dwijnand** [comment]
It will only consider annotated tags (`git tag -a`).

**Comment by NeQuissimus** [comment]
Ah, that was it! Now it does exactly what I wanted :) Awesome, thank you!

**Comment by dwijnand** [comment]
No problem :)
