### ISSUE TITLE
Version number becomes 0.0.0 when commit count exceeds 256

### ISSUE THREAD

**Issue by olafurpg** [dwijnand/sbt-dynver#133]
See https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

<img width="768" alt="Screenshot 2019-12-04 at 10 33 38" src="https://user-images.githubusercontent.com/1408093/70135249-94b98580-1681-11ea-9cdc-b36fa9510f8d.png">

I expected the version number to start with v0.7.6. I'm unable to reproduce locally on my computer, our CI does the releases. You can try to checkout the scalameta/metals repo at commit https://github.com/scalameta/metals/commit/539450ffd3b43f19885e0c2de3c75afe81384871

It looks like this branch is being hit
https://github.com/dwijnand/sbt-dynver/blob/569cd975e77bbfd2163ce792b131dcdd2832321e/src/main/scala/sbtdynver/DynVerPlugin.scala#L113

Any idea what might be going on?

**Comment by raboof** [comment]
perhaps CI did a 'shallow' git checkout and didn't fetch enough history to find the previous tag?

**Comment by dwijnand** [comment]
^

There, in theory, would be a sanity check you opt into for that (https://github.com/dwijnand/sbt-dynver#sanity-checking-the-version) but it needs attention (#132).

**Comment by dwijnand** [comment]
Oh, and `git fetch --unshallow` is a CI agnostic way to avoid this issue.

**Comment by olafurpg** [comment]
Thank you for the help! Let's see how that works out https://github.com/scalameta/metals/pull/1143

**Comment by olafurpg** [comment]
`git fetch --unshallow` seems to have fixed the issue! 
```
] 	published mtags_2.13.1 to https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.13.1/0.7.6+404-2cb4e3b0-SNAPSHOT/mtags_2.13.1-0.7.6+404-2cb4e3b0-SNAPSHOT.jar
```
The readme still recommends  `git fetch --tags` in CI environments so it might be worth a mention. --unshallow is mentioned in the sanity check section.

Thank you!

**Comment by dwijnand** [comment]
:+1: 9d128a8
