### ISSUE TITLE
Unable to resolve version from lightweight tags

### ISSUE THREAD

**Issue by 2m** [dwijnand/sbt-dynver#14]
which are the tags that are created by GitHub when cutting a new release.

Can be fixed by adding `--tags` to the `git describe` command. PR incoming.

**Comment by dwijnand** [comment]
It's a design decision to only consider annotated tags (aka exclude lightweight tags).

I should document that.

But what do you mean by "created by GitHub when cutting a new release"? Aren't GitHub releases based on the user published tags?

**Comment by 2m** [comment]
> Aren't GitHub releases based on the user published tags?

Not necessarily. It is possible to create a new release from [Releases](https://github.com/dwijnand/sbt-dynver/releases/new) GitHub page which will in turn create a new tag. That tag is going to be a lightweight one.

**Comment by 2m** [comment]
Is there a problem when considering lightweight tags in the describe?

**Comment by dwijnand** [comment]
Using lightweight tags to define the version means you can never use tags for anything but the version. For instance you can't create a local "before-refactor" tag, for your convenience, and you have to use SHAs all the time. I personally believe this is a waste of a great feature in git, so I prefer only annotated tags are used for versions.

But I'm happy for sbt-dynver to have an opt-in feature that includes lightweight tags.

**Comment by 2m** [comment]
> ... you can never use tags for anything but the version ...

Are you concerned of a version being inadvertently derived from a tag which was not meant to be a version tag?

`sbt-dynver` uses `--match` to only consider tags that start with a `v` and a number. That should be enough to have this risk very low.

Or is there something else that I am missing?

**Comment by dwijnand** [comment]
You're right, I forgot about that safe-guard - I agree it makes the risk very low.

Go ahead, and welcome, my first contributor :)

**Comment by 2m** [comment]
Fixed by #15
