### ISSUE TITLE
Simplest way to capture the version to a resource?

### ISSUE THREAD

**Issue by jkleckner** [dwijnand/sbt-dynver#141]
Which of the ways would you recommend to write the version string to a resource such as `conf/dynver.txt` or some such?

**Comment by dwijnand** [comment]
You can almost do this with `sbt -Dsbt.supershell=false --error 'print ThisBuild/version'`, but for some reason `ThisBuild` aggregates so you get:

```
sbt-plugin / version
	1.6.0+143-fb3fa8c5
server-javadsl / version
	1.6.0+143-fb3fa8c5
maven-plugin / version
	1.6.0+143-fb3fa8c5
...
client-javadsl / version
	1.6.0+143-fb3fa8c5
ThisBuild / version
	1.6.0+143-fb3fa8c5
```

Personally I would just write a little sbt task to do this.  Eventually we could add something to the plugin.

**Comment by jkleckner** [comment]
Thanks.  I did it with a small task in build.sbt accessing `version.value`

**Comment by dwijnand** [comment]
Cool.  Feel free to share the task example here.  We could eventually add it to the README or in the plugin.  But for now I'll close this issue.

**Comment by jkleckner** [comment]
I'm a bit embarrassed by this quick and dirty hack, but here you go.  Perhaps you can make it nicer...  It creates a resource that can be loaded in `play`.
```
val buildHashTask = TaskKey[Unit]("buildHash", "Create conf/build.hash file")
val buildHashSettings = buildHashTask := {
  name.synchronized {
    val f  = new File("conf/build.hash")
    val rebuild = if (f.exists()) {
      val fh = Process("cat conf/build.hash").lines_!.mkString("")
      val gh = version.value
      fh != gh
    } else {
      true
    }
    if (rebuild) {
      println("gitHashTask: rebuild conf/build.hash")
      IO.write(new java.io.File("conf/build.hash"), version.value)
    }
  }
}

lazy val root = (project in file("."))
  .settings(buildHashSettings, compile in Compile := ((compile in Compile).dependsOn(buildHashTask)).value)
  .enablePlugins(PlayScala)
```
