### ISSUE TITLE
Allow hashtag-in-tag

### ISSUE THREAD

**Issue by eed3si9n** [dwijnand/sbt-dynver#147]
Ref https://github.com/olafurpg/sbt-ci-release/issues/102#issuecomment-586599859

## steps

```
$ git tag v1.4.0-M2#something
$ sbt
....
sbt:IO Root> version
[info] io / version
[info] 	1.4.0-M2#something
[info] version
[info] 	1.4.0-M2#something
```

## problem

version is set to `1.4.0-M2#something`.

## expectation

I'd like the version to be set to `1.4.0-M2` removing `#` and subsequent letters.

**Comment by dwijnand** [comment]
Here's how you can post-process the string, to customize it: https://github.com/dwijnand/sbt-dynver#custom-version-string.
