### ISSUE TITLE
Avoid using `+` sign in artifact names by default

### ISSUE THREAD

**Issue by ignasi35** [dwijnand/sbt-dynver#161]
Using the `+` character in the version snowballs into multiple hard-to-track issues:

- [when using it as a tag in docker](https://github.com/lagom/lagom-samples/blob/1.6.x/shopping-cart/shopping-cart-scala/build.sbt#L23-L25)
- [when publishing a gradle plugin](https://github.com/gradle/gradle/issues/13445)

While I like the readability of `"1.0.0-M1+37-732f2dee"` I think variants like `"1.0.0-M1_37-732f2dee"` or even "1.0.0-M1_37_732f2dee" are good enough.

**Comment by ignasi35** [comment]
RTFM !

https://github.com/dwijnand/sbt-dynver#docker-compatible-version-strings

**Comment by ignasi35** [comment]
On second thought. Even as I've read the manual, I think the defaults should be a bit _safer_. People are unlikely to publish gradle plugins but they are very likely to produce docker images. I think the next major of `sbt-dynver` could consider switching the defaults to avoid `+`.

**Comment by dwijnand** [comment]
> While I like the readability of `"1.0.0-M1+37-732f2dee"` I think variants like `"1.0.0-M1_37-732f2dee"` or even "1.0.0-M1_37_732f2dee" are good enough.

I, respectfully, disagree.  But I'm happy to find ways to make sure users are aware and know how to change the choice.
