### ISSUE TITLE
assertion failed: Incoherence: dynverTagPrefix=v vs dynverVTagPrefix=false

### ISSUE THREAD

**Issue by ignasi35** [dwijnand/sbt-dynver#169]
Upgrading from `4.0.0` to `4.1.0` a project with the setting:

```
dynverVTagPrefix in ThisBuild := false
```

causes the project to not load with the error:

```

[info] loading settings for project twirl from build.sbt ...
[error] java.lang.AssertionError: assertion failed: Incoherence: dynverTagPrefix=v vs dynverVTagPrefix=false
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
(see for example https://travis-ci.com/github/playframework/twirl/jobs/355362477) 

The workaround is to opt out of the (old) `dynverVTagPrefix` and, instead, set `dynverTagPrefix=""`. See the [release notes](https://github.com/dwijnand/sbt-dynver/releases/tag/v4.1.0).

**Comment by ignasi35** [comment]
Hmm, sometimes the error is not printed? (https://travis-ci.com/github/lagom/lagom/jobs/355355692#L267)

**Comment by dwijnand** [comment]
That's my bad.  I really should've tested that check.  Of course it's going to throw... :-/

I'll try to fix this tomorrow.

**Comment by ignasi35** [comment]
Thanks @dwijnand for the quick fix.
