### ISSUE TITLE
Allow getting full Git commit hash

### ISSUE THREAD

**Issue by marko-asplund** [dwijnand/sbt-dynver#199]
`dynverGitDescribeOutput` can be used to fetch the Git commit hash suffix, but not the full commit hash.
In some cases users might want to use the full commit hash instead of the suffix.

**Comment by dwijnand** [comment]
sbt-dynver just shells out to `git`, so you can just do the same.  Here's how it's done internally for the purposes of getting the short sha for the version: https://github.com/dwijnand/sbt-dynver/blob/5214ab803a799495f5fa47ddad08a9719a60b330/dynver/src/main/scala/sbtdynver/DynVer.scala#L164.
