### ISSUE TITLE
isSnapshot isn't what I thought....

### ISSUE THREAD

**Issue by fommil** [dwijnand/sbt-dynver#23]
I didn't expect this to be false:

```
| when on tag v1.0.0 +3 commits, on commit 1234abcd, w/o local changes | 1.0.0+3-1234abcd               | false 
```

how can I detect when I'm on anything other than a tagged commit with no local changes?

**Comment by fommil** [comment]
I have a workaround, if there is a `+` in the version then I can consider it a snapshot.

But there is still this issue that sonatype snapshots repo might reject it if the version string doesn't end with `-SNAPSHOT`

**Comment by dwijnand** [comment]
This is the more debatable one I was telling you about.

The reason is I consider isSnapshot as telling me if this is a stable version string or not. 1.0.0-SNAPSHOT isn't stable, but 1.0.0+3-1234abcd is. I can release that to the world, cache it on every CDN and not run into trouble.

But I might be in the minority on this. I need to check where this case falls in sbt-git.

**Comment by fommil** [comment]
How about introducing a new key "isTaggedVersion"? That'll do for me.

**Comment by dwijnand** [comment]
Sounds really specific, and one of a number of values one could introduce (isTaggedDirtyVersion, isDirtyVersion, etc etc). I'm not sure I want to go down this route.

I think you should redefine `isSnapshot in ThisBuild` in terms of the values in `dynverGitDescribeOutput.value`, differently than how I do be default.

**Comment by dwijnand** [comment]
Been thinking more about the semantics of `isSnapshot`. I realise that the case we're talking about is exactly about the interpretations of `isSnapshot`. Sadly the description of `isSnapshot` does really help: "True if the the version of the project is a snapshot version.".

As I said, I've been playing with the idea that it should determine if the version is a stable identifier or not. You're utilising it to determine if it's a release version or not. I don't think either semantic meanings are wrong, but this case is true for one and false for the other, respectively.

**Comment by SethTisue** [comment]
> I consider isSnapshot as telling me if this is a stable version string or not

fwiw, that was my expectation as well

**Comment by EmilDafinov** [comment]
Any updates on that issue? For me also it is weird that a version of the commit that is not tagged is counted as non-snapshot: for example, if I'm using Bintray / Artifactory I would like to automatically push snapshot versions to artifactory and the non-snapshot versions to bintray. However, a build created on Travis would never be a snapshot version, since there are never local changes. On, at least in my mind, builds of PRs for example should be considered development versions (snapshots) before they are merged to master.

**Comment by dwijnand** [comment]
We're suffering from the documentation of `isSnapshot` being unclear. I'm considering switching behaviour. But what I can definitely try and do in the meanwhile is describe how to redefine isSnapshot to follow your semantic meaning, using dynverGitDescribeOutput.

**Comment by EmilDafinov** [comment]
That would be great :) 👍

**Comment by EmilDafinov** [comment]
On a somewhat unrelated note(just typing out loud here;): if isSnapshot could either mean "not a stable identifier" or "not a release version", I think a flag like`isReleaseVersion` would be rather unambiguous in meaning and would allow @fommil and me to use the plugin for our use case, while allowing the current semantics of `isSnapshot` to remain unchanged. It is not as specific as `isTaggedVersion`. On the other hand, if `isSnapshot` ever changes semantics down the road to become the opposite of `isReleaseVersion`, having the two would still be a very nice syntactic sugar for people that want to make their builds more readable to their taste (the same way we have both `isEmpty` and `nonEmpty` defined on collections).

**Comment by dwijnand** [comment]
I believe this should do it:

```scala
isSnapshot := {
  val x = dynverGitDescribeOutput.value
  (x.ref.value startsWith "v") && (x.commitSuffix.distance <= 0 || x.commitSuffix.sha.isEmpty)
}
```

**Comment by fommil** [comment]
Honestly, I worked around this month's ago. Though if my workaround gets cleaner that'd be cool, but this is working awesomely for my workflow.

**Comment by jvican** [comment]
Is it possible to let users override the `isSnapshot` method in `GitDescribeOutput`? Adding a custom flag as a class parameter that can be then tweaked by the users would be useful.

**Comment by raboof** [comment]
I also expected `isSnapshot` to be `true` when commits have been added to the tag.

I agree this boils down to the semantics of `isSnapshot`: is it the opposite of a 'release' (roughly as in maven/ivy/github lingo) or does it stand for 'unstable identifier' (in caching/CDN terms)?

While I appreciate neither interpretation is 'clearly correct' (or 'clearly wrong') and definitely see the value of 'stable' version strings (one of the main reasons for using dynver after all :) ), I interpret `isSnapshot` in the 'opposite of a release' sense.

I'm having a hard time coming up with a good name for a key distinguishing 'ambiguous' version strings from 'stable' ones, though...

**Comment by raboof** [comment]
sbt-git also interprets `isSnapshot` as 'not tagged or no uncommited changes (https://github.com/sbt/sbt-git/blob/fc5be10bee7b8242d3b097f7c9a9b09b0c3f246e/src/main/scala/com/typesafe/sbt/SbtGit.scala#L186)

`distinctVersion`? Shall I prepare a PR?

**Comment by dwijnand** [comment]
Fixed in 2.0.0, which I'll cut tomorrow.

**Comment by fommil** [comment]
oh, nice! Now I have to undo my hacks :smile:

**Comment by EmilDafinov** [comment]
Hurrah:)
