### ISSUE TITLE
customise version strings?

### ISSUE THREAD

**Issue by fommil** [dwijnand/sbt-dynver#24]
I'd like to have the versioning of:

1. if I'm on a tag, clean it up (e.g. remove a trailing `v`) and use it
2. if I'm on a clean commit, just use the hash
3. if I'm on a dirty commit, add `-local` or something

is this possible?

I'm having problems publishing the auto generated commits to sonatype snapshots. I think the `+` might be causing a 400 error.

**Comment by fommil** [comment]
ok, I have a workaround that is compatible with #23 ... I run this on my CI

```
git tag | xargs git tag -d
```

which removes all tags, and that means it defaults to the `isSnapshot = true` case where the version is the git hash. Exactly what I want!

I only do versioned releases from my desktop.

**Comment by dwijnand** [comment]
This is related to #5, but with more flexibility. That's fine because I wanted to provide a flexible solution to the problem space anyways. I started working towards that with #11, but I never finished completely.

**Comment by fommil** [comment]
this morphed into the need to add `-SNAPSHOT` at the end of version strings for me.

**Comment by dwijnand** [comment]
@fommil Would you mind verifying for me that the docs at https://github.com/dwijnand/sbt-dynver#custom-version-string are clear and obivous, and provide a suitable solution to your problem? Just make sure you update to version `1.1.1+9-bd70cc00`.

**Comment by fommil** [comment]
oh cool, I'll try to do this after work tonight. If not, remind me again at scalasphere.

**Comment by dwijnand** [comment]
Cut as v1.2.0

**Comment by fommil** [comment]
docs look good! Although I am a little scared by how much code I have to write to customise that version string :smile: 

```scala
    version := {
      val v = version.value
      if (!v.contains("+")) v
      else v + "-SNAPSHOT"
    }
```

**Comment by fommil** [comment]
maybe I should refer to `dynver.value` here instead of `version.value`

**Comment by dwijnand** [comment]
`dynver` is the task, `version` is the setting. So one is memoised and stable, the other one is more correct, but varies on each call (depending on the state of the repo, working directory and time).

The amount of code.. yeah... it's tragic. Some of it is little mistakes here, but a big problem is the hard divide between settings and tasks.

**Comment by joan38** [comment]
I which either sbt-dynver set `-SNAPSHOT` automatically or Maven repos didn't enforce this `-SNAPSHOT` ending.

**Comment by dwijnand** [comment]
Basically sbt-dynver is anti-SNAPSHOT.

**Comment by joan38** [comment]
Fair enough

**Comment by fommil** [comment]
Hehe a look at what i do it sbt-sensible

**Comment by SethTisue** [comment]
> Hehe a look at what i do it sbt-sensible

we can't, you deleted it
