### ISSUE TITLE
Consider and find a way to move DynVer to autoImport

### ISSUE THREAD

**Issue by dwijnand** [dwijnand/sbt-dynver#29]

**Comment by jvican** [comment]
In my opinion, it's fine the way it is, I would not expect people to fiddle with `DynVer` in their `build.sbt`. For instance, I did not expect it to be auto imported.
  
IMO, the less names in the auto imported scope, the better.

**Comment by Daenyth** [comment]
This is done I think?

**Comment by dwijnand** [comment]
Yep, this needn't happen and there's reason for it not to.
