### ISSUE TITLE
1.0.0-M5 release?

### ISSUE THREAD

**Issue by olafurpg** [dwijnand/sbt-dynver#38]
Would it be possible to get a release for sbt 1.0.0-M5? Now that sbt-coursier supports 1.0.0-M5 I can almost migrate my builds to it :)

**Comment by dwijnand** [comment]
@olafurpg I'll try and complete this work over the weekend.

**Comment by dwijnand** [comment]
Done. v1.3.0 https://github.com/dwijnand/sbt-dynver/releases/tag/v1.3.0

**Comment by olafurpg** [comment]
Thank you @dwijnand !
