### ISSUE TITLE
simple task to write out version to disk

### ISSUE THREAD

**Issue by fommil** [dwijnand/sbt-dynver#41]
It would be useful to have a task that can write out the dynver to disk for use in CI (I know it's trivial to write it, so it's more a question of if you want to have it or not)

Very much related to #2 but for a different workflow where a CI tool may need access to the version to trigger a downstream job.

**Comment by dwijnand** [comment]
Eh. As you say, sounds trivial and I'm not sure how common/niche of a use case it's fixing to bundle it. But I could be persuaded with a PR..

**Comment by fommil** [comment]
btw we are using

```scala

    dynverFile := file("version"),
    dynverWrite := {
      val out = dynverFile.value
      val v = version.value
      IO.write(out, v)
    },
...
  val dynverFile = settingKey[File]("File used by dynverWrite")
  val dynverWrite = taskKey[Unit]("Writes out the version to a file")
```

**Comment by dwijnand** [comment]
Looks good. Send a PR.
