### ISSUE TITLE
RFE: ability to override version with -Ddynver.version=x.y.z

### ISSUE THREAD

**Issue by olafurpg** [dwijnand/sbt-dynver#43]
I've noticed I keep adding the same customization when using sbt-dynver

```scala
version.in(ThisBuild) := sys.props.getOrElse("foo.version", version.in(ThisBuild).value)
```

When I publish locally, I do `sbt -Dfoo.version=0.1.0 release` and create/push the tag only after a successful release. It would be nice if sbt-dynver specified a system property by default which can override the calculated version number.

**Comment by dwijnand** [comment]
I'd be happy to accept such an enhancement.

**Comment by olafurpg** [comment]
Cool, what do you think would be a good sys.prop name?

**Comment by dwijnand** [comment]
sbt-git uses "project.version". I don't think "dynver.version" is terrible, so I'm happy to go with that.

**Comment by olafurpg** [comment]
This didn't turn out be necessary.
