### ISSUE TITLE
isVersionStable could be a setting

### ISSUE THREAD

**Issue by laughedelic** [dwijnand/sbt-dynver#49]
`isVersionStable` key is defined as a task, but then defined as

https://github.com/dwijnand/sbt-dynver/blob/7edb3e18d2b06a5629be5bf927e45dc96c11cd7d/src/main/scala/sbtdynver/DynVerPlugin.scala#L26

i.e. using `dynverGitDescribeOutput` which is a setting. So unless there is some other reason for this key to be a task, I suggest to change it to setting. It would also make it more similar to `isSnapshot` and usable in other settings.

**Comment by dwijnand** [comment]
Good idea. This is a good first issue if anyone wants to contribute.
