### ISSUE TITLE
the + in version is not compatible with docker tags

### ISSUE THREAD

**Issue by xelax** [dwijnand/sbt-dynver#5]
When combining sbt-dynver with sbt-native-packager it creates versions that are not compatible with docker tag names: 
"A tag name may contain lowercase and uppercase characters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters."

this is the error I am getting:

```
invalid argument "blah.com/real-mine:1.0.0+5-abeb6d22" for t: Error parsing reference: "blah.com/real-mine:1.0.0+5-abeb6d22" is not a valid repository/tag
```

**Comment by dwijnand** [comment]
Using `+` for me is one of the benefits over git describe as it conveys the meaning much clearly.

But I think I can structure the data the forms the version such that you can define the final version string any way you want.

**Comment by fommil** [comment]
I think the version string might also be incompatible with sonatype snapshots repo: I'm getting this kind of thing a lot

```
[error] (*:publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/fommil/spray-json-shapeless_2.11/1.3.0%2B12-61164ab5%2B20161121-2145/spray-json-shapeless_2.11-1.3.0%2B12-61164ab5%2B20161121-2145.pom failed with status code 400: Bad Request

```

**Comment by daddykotex** [comment]
I use `sbt-docker` but could solve the issue by adding this to my build:
```
imageNames in docker := {
  (imageNames in docker).value.map(img => img.copy(tag = img.tag.map(_.replace("+", "_"))))
}
```

Note that `imageNames` is already filled here by a internal plugin. There are two images one with the tag latest and one with the version. Here I simply override the settings with the current value but I replace any `+` in the tag.

There is probably a similar way to do this with `sbt-native-packager`.

**Comment by dwijnand** [comment]
Hi all,

The solution, as documented in the top half of https://github.com/dwijnand/sbt-dynver#custom-version-string is to post-process, like so:

```scala
version in ThisBuild ~= (_.replace('+', '-'))
 dynver in ThisBuild ~= (_.replace('+', '-'))
```

See the rest of https://github.com/dwijnand/sbt-dynver#custom-version-string for guidance if you want/need a more sophisticated solution.
