### ISSUE TITLE
Versioning compatibility with ivy2/maven wildcard patterns for first snapshot build after tag

### ISSUE THREAD

**Issue by lokkju** [dwijnand/sbt-dynver#52]
I'm loving this plugin, but I'm looking for a way to easily use it with dependency wildcard patterns in ivy and maven.

the current versioning pattern means that the first "snapshot" version after a tag is `0.0.1+20171207-1200` ; while the first committed version after a tag is `0.0.1+1-01234abcd`

This means that a version spec like "0.0.1+" will select the older, snapshot, version over the newer version.

This could be solved just by changing the first snapshot build after a tag to use `0.0.1+0+20171207-1200`

I know I can customize my version string - but this seems like a wide use case.

**Comment by dwijnand** [comment]
Interesting.

Here are the relevant cases:

```
1.0.0+20140707-1030
1.0.0+3-1234abcd
1.0.0+3-1234abcd+20140707-1030
```

Perhaps we can change that first one so it's:

```
1.0.0+0-00000000-20140707-1030
1.0.0+3-1234abcd
1.0.0+3-1234abcd+20140707-1030
```

**Comment by lokkju** [comment]
Yup, that should work perfectly.
