### ISSUE TITLE
Add support for multiple sub-projects in the same Git repo

### ISSUE THREAD

**Issue by eliaslevy** [dwijnand/sbt-dynver#61]
Would require per sub-project configuration and being able to match the different version tags for each subproject (e.g. `foo-v1.0.0`, `bar-0.5.0`) and pass the right glob to `git describe --match`.

**Comment by dwijnand** [comment]
I'm hesitant to add this support. For one because I think (but I'm not sure) it goes against what sbt expects.

However if someone can implement this, and the change isn't that big, I might reconsider.

**Comment by eliaslevy** [comment]
See #62.

**Comment by dwijnand** [comment]
Fixed by #158

**Comment by LeifW** [comment]
This doesn't seem fixed at all? `dynverTagPrefix` is still scoped to `ThisBuild`, so it can't vary per-subproject.

**Comment by touchdown** [comment]
> This doesn't seem fixed at all? `dynverTagPrefix` is still scoped to `ThisBuild`, so it can't vary per-subproject.

yah i just maintain my own jar with this change
```
-  override def buildSettings = Seq(
+  override def projectSettings = Seq(
```
