### ISSUE TITLE
Release tagged version

### ISSUE THREAD

**Issue by leonardehrenfried** [dwijnand/sbt-dynver#67]
I know that i can use version `2.1.0+9-b74a6a57` but would still be nice to have 2.2.0.

**Comment by dwijnand** [comment]
hey @leonardehrenfried,

I've been wanting to get back to sbt-dynver, to finish working with @eliaslevy in #62.

part of the reason I don't push a tag right now is I'm not sure if with your #63 if it should be sbt-dynver 3.0.0.. wdyt?

**Comment by leonardehrenfried** [comment]
Hmm, on the one hand it is hard to imagine how somehow someone could rely on the absence of the `+0` and whose workflow is now broken.

On the other hand, I would err on the side of caution and bump the number to 3.0.0. Version numbers don't cost anything and I don't see any downsides to the bump.

**Comment by dwijnand** [comment]
Good point. Let's go with 3.0.0.

**Comment by dwijnand** [comment]
https://github.com/dwijnand/sbt-dynver/releases/tag/v3.0.0
