### ISSUE TITLE
include the number of commits for the 'no tags' case as well

### ISSUE THREAD

**Issue by raboof** [dwijnand/sbt-dynver#72]
I love how in the 'versioned' case, version numbers like `1.0.0+3-1234abcd` provide some intuition of how far this version is from the last tag.

When there are no version tags in the history, we lose that information. I think it would be useful to add it in that case as well, counting the number of commits up to this commit. Instead of `1234abcd+20140707-1030` or `1234abcd` we'd get `3-1234abcd+20140707-1030` or `3-1234abcd`.

**Comment by dwijnand** [comment]
I think this is a good idea. Pull request welcome.
