### ISSUE TITLE
How to activate SonatypeSnapshots?

### ISSUE THREAD

**Issue by mrt181** [dwijnand/sbt-dynver#80]
I have tried this but it does not work:

```sbt
lazy val root = (project in file("."))
  .enablePlugins(JavaAppPackaging, BuildInfoPlugin, DynVerPlugin)
  .settings(
    name := "apiScala",
    buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
    dynverSonatypeSnapshots := true,
    commonSettings,
    compilerSettings
)
```

but `sbt version` returns a version missing the suffix `1.2.0+20-4184321d+20181023-2220` with uncommited changes
`git describe --dirty` returns this `1.2.0-20-g4184321-dirty`

**Comment by dwijnand** [comment]
Set `dynverSonatypeSnapshots in ThisBuild := true`.
