### ISSUE TITLE
Different versions when Cross-publishing

### ISSUE THREAD

**Issue by ThijsBroersen** [dwijnand/sbt-dynver#84]
When I cross-publish my 'snapshot' project it creates a dynver for each Scala version (different timestamps). Is it possible to create a dynver only once and reuse for a list of tasks?

**Comment by dwijnand** [comment]
Use `version` (`version in ThisBuild`, to be precise) if you want something stable across multiple command runs.  `dynver` is intentionally a task key, which means it can change.
